- name: Install Neutron in Networking Node
  yum:
    name:
      - openstack-neutron-linuxbridge ebtable ipset
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install Horizon in Networking Node
  yum:
    name:
      - openstack-dashboard
    state: latest
  when: ansible_distribution == "CentOS"
